name: github pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          submodules: true

      - run: ls && pwd && ls github-markdown-css && ls /home/runner/work/home/home/./github-markdown-css/

      - run: |
          npm i
          npm run build:tailwindcss

      - name: setup trunk
        uses: jetli/trunk-action@v0.4.0
        with:
            version: latest

      - name: build src
        run: |
          rustup target add wasm32-unknown-unknown
          trunk build --release --public-url .

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          publish_dir: ./dist
