name: yarn auto formatter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    formatter:
        name: formatter
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v3

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: latest

            - name: Install
              run: yarn

          - name: Run Format
            run: yarn fmt

          - uses: stefanzweifel/git-auto-commit-action@v4
            with:
              commit_message: '[Action] yarn fmt'
